export type GetProviders = () => Promise<string[]>

export const buildGetProviders = (): GetProviders => async () => [
  'OpenAI',
  'Anthropic',
  'HuggingFace',
  'Together',
  'DeepInfra',
  'Azure',
  'Modal',
  'AnyScale',
  'Replicate',
  'Perplexity',
  'Recursal',
  'Fireworks',
  'Mistral',
  'Groq',
  'Cohere',
  'Lepton',
  'OctoAI',
  'Novita',
  'DeepSeek',
  'Infermatic',
  'AI21',
  'Featherless',
  'Lambda',
  'Avian',
  'SambaNova',
  '01.AI',
  'Google',
  'Google AI Studio',
  'Mancer',
  'Mancer 2',
  'Hyperbolic',
  'Hyperbolic 2',
  'Lynn 2',
  'Lynn',
  'Reflection'
]
